### PR TITLE
Changes for Anaphora Resolution

### PR DESCRIPTION
**Pull request by khannatanmai**
These changes are made to add a side "ref" to a Lexical Unit and to make it possible to clip side ref.

The apertium-anaphora module adds the antecedent for an anaphor on the side ref and in transfer, the output word is changed based on the antecedent in side "ref" and hence we need to add the ability to clip side ref.

### CODE REVIEW

**Comment by unhammer** [comment]
LGTM. 

(I was about to ask what about the cases where `preBilingual==false` in https://github.com/apertium/apertium/blob/890357653f6556d64e54f3485edb280d80f12126/apertium/transfer.cc#L2350 and https://github.com/apertium/apertium/blob/890357653f6556d64e54f3485edb280d80f12126/apertium/transfer.cc#L2283 but then http://wiki.apertium.org/wiki/Anaphora_Resolution_Module does say that the anaphora module has to be after lexical selection which implies that `apertium-transfer` is used with `-b` . Maybe http://wiki.apertium.org/wiki/Anaphora_Resolution_Module#Anaphora_Resolution_in_Apertium should have some explicit command line examples though, `$ echo `^foo/bar/ref$ ^…$ | apertium-stuff` + what the output is, and some example lines from `modes.xml`)

**Comment by khannatanmai** [comment]
@unhammer I was wondering what to do there but like you said, it has to be after LexSel so I simply sent an empty ref string to TransferWord, as there really didn't seem to be another option.

I'm not sure exactly what command line examples do you want me to put?

**Comment by unhammer** [comment]
Your docs have examples of command line input and output, but not of the commands used, `$ apertium-transfer -b foo.t1x foo.t1x.bin < input.txt ` and similar

**Comment by khannatanmai** [comment]
@unhammer does this README have what you're looking for?
https://github.com/apertium/apertium-anaphora/blob/master/README

**Comment by unhammer** [comment]
I meant similar to how http://wiki.apertium.org/wiki/A_long_introduction_to_transfer_rules#Lexical_transfer shows inputs, outputs and invocations

**Pull request merged**
