### PR TITLE
Capitalization Post-processor

### PR DESCRIPTION
**Pull request by mr-martian**
As suggested in #67, this PR is an attempt at creating a simple module for handling capitalization so that modules other than analysis can from now on completely ignore capitalization or expect exact matches.

So far, I have made a pre-processor that should probably go after the tagger:

```bash
$ echo '[[t:xyz]]^HELLO/hello<ij>$ ^bcd/Bcd<n>/EDF<v>$^,/,<cm>$' | apertium/apertium-extract-caps 
[[t:xyz; c:AA/aa]]^hello<ij>$ [[c:aa/Aa]]^Bcd<n>$[[c:aa/aa]]^,<cm>$
```

Then there will be a second module after postgen which uses these wblanks to set the appropriate capitalization.

The rules for this second module would have access to these wblanks and the target language capitalization of the word as well as this information for some number of adjacent words.

Questions:
* Is there any other information the second module might need?
  * Like maybe whether the current sentence originally began with a capital
* When wblanks get merged by lsx or postgen,
  * How do we determine what the words are? (list of characters to split on?)
  * How do we determine which wblank goes with which word?

For the last question, all I've come up with so far is that if there's more wblank specifiers than segments, to have the option to assign either from the left or from the right, which will probably cover a lot of cases, but I don't know if there's any obvious one's that would miss.

### CODE REVIEW

**Comment by unhammer** [comment]
Interesting! And we keep lemmas dictionary-cased throughout the pipeline? I think it should work, if the second module can have some lemma/PoS-specific rules and access to at least one LU of context.

Some challenges in general:

* All German nouns should be capitalised, Norwegian common nouns typically not. In English, language names should be capitalised, in Norwegian not.
* Some times even more nuanced, `^De Masuriske Søer<np><top>$` in Danish should be `Dei masuriske sjøane` in Norwegian
* In many languages, names like `iPhone` should keep their casing everywhere (even at start of sentence)
* Not all periods are sentence breaks (e.g. "third" is written `3.` in Norwegian).
* In nob→nno `KRF` should become `KrF` everywhere
* In nob→nno `^Døperen Johannes<np>$` should become `døparen Johannes` except at start of sentence.

**Comment by mr-martian** [comment]
> And we keep lemmas dictionary-cased throughout the pipeline?

Yes.

> I think it should work, if the second module can have some lemma/PoS-specific rules and access to at least one LU of context.

So if you want POS tags in the second module, that suggests switching generation to `lt-proc -b`, which actually makes things significantly easier with regard to what I had in mind for the new module, though it does create problems for postgen.

A possible way forward is to adjust `lsx-proc` so that it can handle inputs like `^iPhone<np><sg>/iPhone$` and also apply rules repeatedly until none match, at which point the various Romance languages could be rewritten in probably much-simplified form using this. (That's 2 fairly simple changes, both of which I might be able to implement tomorrow.)

> Some challenges in general:

If I'm reading these right, I think several of these could be handled by comparing SL surface case, SL lemma case, and TL lemma case, all of which are available.

> All German nouns should be capitalised, Norwegian common nouns typically not. In English, language names should be capitalised, in Norwegian not.

That's why I included both surface and lemma capitalization in the wblank - so there's some indication of whether things are capitalized for lexical reasons or not.

> Not all periods are sentence breaks (e.g. "third" is written 3. in Norwegian).

Is that 1 LU or 2?

**Comment by unhammer** [comment]
>> Not all periods are sentence breaks (e.g. "third" is written 3. in Norwegian).

> Is that 1 LU or 2?

1 if it's the ordinal, 2 if it's a number followed by period `^3./3.<adj><ord>/3<det><qnt>+.<sent>$` (but the disambiguator handles that). I don't know if there are languages that have periods that should be one LU but also not affect caps (of course, if I quote it like “.” then the following word should be `then` and not `Then` but that's getting into very unlikely territory :))

**Comment by MarcRiera** [comment]
> So if you want POS tags in the second module, that suggests switching generation to `lt-proc -b`, which actually makes things significantly easier with regard to what I had in mind for the new module, though it does create problems for postgen.

Many pairs (`apertium-nno-nob`, `apertium-spa-cat` and others) have already implemented a generation preferences module (CG) between generation and postgen. Generation uses `lt-proc -b` and the preferences module uses `cg-proc -n -g` to only output the selected form and strip away `^` and `$`. If that's the problem you had in mind for postgen, you may want to try doing something similar.

**Comment by mr-martian** [comment]
Actually the reason I started on this now was because I couldn't figure out how to handle case properly within postgen and so was trying to handle it after postgen. Thus my initial assumption was that this module would not be operating on `^...$` blocks but rather on plain text.

On the other hand, as I noted, -separable can, with a few small additions, do everything that postgen now does, while keeping the delimiters.

**Comment by mr-martian** [comment]
So the proposed pipeline would be

| command | use |
|------|--------|
| `lt-proc -b` | generator |
| `cg-proc` | preferences |
| `lsx-proc -p` (or something) | postgen |
| `apertium-restore-caps` | capitalization |

So the first 3 would all output `^analysis/surface$` and the final step would output just `surface` (or `Surface` or `SURFACE`).

**Comment by mr-martian** [comment]
It occurs to me that the rules in the final step could have roughly the same syntax and semantics as LRX:

```xml
<capitalization use="left">
  <!-- if the last 2 words were originally all-caps, this one probably should be too -->
  <rule weight="1.0">
    <match scap="AA"/>
    <match scap="AA"/>
    <match scap="AA"><select cap="AA"/></match>
  </rule>
  <!-- iPhone should use dictionary case when not all-caps -->
  <rule weight="0.9">
    <match lemma="iPhone"><select src="dix"/></match>
  </rule>
</capitalization>
```

**Comment by unhammer** [comment]
I like it :-) 

Btw, would iPhone get scap `aA`? Then one could select dix on scap aA as a general fallback

**Comment by mr-martian** [comment]
So far I was using the same capitalization processing as the existing tools, which have `AA`, `aa`, and `Aa` as the only possibilities (so, check first char and last if the first is upper).

Just checking first and last characters would actually mark iPhone as `aa`, but we could instead use the full sequence and mark iPhone as `aAa` and then write your rule with `<match dcap="aA*">`.

The problem then is what to do with rules that change the caps to something other than `AA/aa/Aa`. On the other hand, that's likely to be a rare enough case that "do something consistent, even if a little weird" is probably adequate (since I'm not sure how to consistently disallow that).

```
caps: AaAa
and -> AnD
plot -> PlOt
example -> ExAmple
```

Oh, and examples like `Dei masuriske sjøane` could have caps `Aa a a` (with spaces).

Unless anyone has a better idea, I'll see about implementing this and we can try it out.

**Comment by unhammer** [comment]
We could have a difference between readable and writable types of caps, so aa, Aa and AA are rw but aA (wEirdCase) is only readable

**Comment by mr-martian** [comment]
```xml
<?xml version="1.0"?>
<capitalization>
	<rules>
		<rule weight="0.1">
			<match select="aa"/>
		</rule>
		<rule weight="1.0">
			<or>
				<match lemma="iPhone" select="dix"/>
				<match lemma="iPod" select="dix"/>
			</or>
		</rule>
		<rule weight="0.9">
			<match tags="np.*" select="Aa"/>
		</rule>
	</rules>
</capitalization>
```

```bash
$ apertium/apertium-compile-caps tests/data/basic.crx crx.bin
$ cat blah.txt
[[c:AA/AA]]^xyz<vblex>/XyZ$ ^qry<adj>/Qry$
^iPhone<np><top>/iPhone$
^Daniel<np><ant>/Daniel$
$ cat blah.txt | apertium/apertium-restore-caps crx.bin
[[c:AA/AA]]xyz[[/]] qry
iPhone
Daniel
```

Available attributes for `<match>` are `lemma`, `tags`, and `surface` for literal values (case-sensitive) and `srcsurf`, `trgsurf`, `srclem`, and `trglem` for just capitalization. The `select` attribute can be `dix`, `AA`, `Aa`, or `aa`.

Feel free to suggest better names for any of this. I'll try to add more complete examples/tests maybe tomorrow.

**Comment by mr-martian** [comment]
I think that this module will require more features to be used at the scale of an entire pair, but I'm not confident of what those features are, so I'm inclined to release this as-is and add further features based on features as the need arises unless anyone objects.

**Pull request merged**
