### PR TITLE
 Implement <reject-current-rule shifting="N"/>

### LINKED ISSUE #194: <reject-current-rule shifting="N"/> for lookahead of >2 word rules
I would like to do something like
```
<reject-current-rule shifting="4"/>
```
to shift up until the last word of a five-pattern rule, in order to get lookahead.

Currently we can do 

```
<reject-current-rule shifting="yes"/>
```
which will drop out of processing the current rule, and start processing afresh as if we had processed only the first pattern-item. I want, in my five-pattern rule, to start processing afresh as if we had processed the first four pattern-items.

### PR DESCRIPTION
**Pull request by unhammer**
where N is a pattern-item position; this lets us use it for lookahead on rules of more than two pattern-items:

```xml
    <rule comment="transpose word 3 and 4; lookahead on word 5">
      <pattern>
        <pattern-item n="pasvsubj"/>    <!-- den -->
        <pattern-item n="aux"/>         <!-- blir -->
        <pattern-item n="pasv-pp"/>     <!-- driven-->
        <pattern-item n="adv_unbound"/> <!-- i dag -->
        <pattern-item n="prep"/>        <!-- Ensure following preposition -->
      </pattern>
      <action>
        <out>
          <chunk><clip pos="1" part="whole"/></chunk> <b/> <!-- den -->
          <chunk><clip pos="2" part="whole"/></chunk> <b/> <!-- blir -->
          <chunk><clip pos="4" part="whole"/></chunk> <b/> <!-- i dag -->
          <chunk><clip pos="3" part="whole"/></chunk> <b/> <!-- driven -->
        </out>
        <reject-current-rule shifting="4"/>
      </action>
    </rule>
```

(we typically want the last preposition to be the start of noun phrase rules)

Fixes #194

So far 436233 nob-nno corpus lines have processed without any diffs (when not using this feature, just checking for backwards-compatibility), so doesn't seem to introduce any regressions. But @hectoralos do you have a test set I should try?

### CODE REVIEW

**Comment by hectoralos** [comment]
Good job! But no, I don't have any.

**Review by mr-martian — APPROVED** [review]
LGTM

**Comment by mr-martian** [comment]
When I need a large regression test for lttoolbox or apertium, I use `apertium-oci/corpus/jornalet.5000.txt` and `apertium-fra/corpus/wikipedia.5000.txt` as inputs to `oci-fra` and `fra-oci` and check for diffs.

**Comment by unhammer** [comment]
No diffs there either :)

**Pull request closed without merging**
