### PR TITLE
Fix bug introduced in ODT translation (605540d93)

### PR DESCRIPTION
**Pull request by xavivars**
Introduced in https://github.com/apertium/apertium/commit/605540d934d698bb71d0d09e06eb8bf4f5ffba48#diff-81172e11cabd02a4ab9c27131519d378

### CODE REVIEW

**Comment by xavivars** [comment]
I've also added some tests, to prevent this to happen again.

**Comment by xavivars** [comment]
Tests are passing in my local machine.... :|

**Comment by TinoDidriksen** [comment]
Merged, but unfortunately it doesn't build on a pristine setup:
````
FAIL: odt/run

error [in.odt]:  missing 1 bytes in zipfile
  (attempting to process anyway)
error: invalid zip file with overlapped components (possible zip bomb)
../../apertium/apertium: line 149: /usr/bin/apertium-desodt: No such file or directory
../../apertium/apertium: line 159: /usr/bin/apertium-reodt: No such file or directory
````

Tests are run before install, and the apertium script can't currently handle that.

**Comment by unhammer** [comment]
b0afc3f18a9f436515b415f17a73fc77df08eef5 fixes that, though on my machine I see

```

FAIL: odt/run
=============

error [in.odt]:  missing 1 bytes in zipfile
  (attempting to process anyway)
error [in.odt]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
  (attempting to re-compensate)
/tmp/apertium.wb5QlGi9/Thumbnails/thumbnail.png  bad CRC a5295fec  (should be c68d23ff)
file #17:  bad zipfile offset (local header sig):  6925
  (attempting to re-compensate)
--- out.odt
+++ expected.odt
-        553 a5295fec Thumbnails/thumbnail.png
+        553 c68d23ff Thumbnails/thumbnail.png
FAIL odt/run (exit status: 1)

```

**Comment by xavivars** [comment]
@TinoDidriksen: you're right, I had installed it before running the tests, that's why it was passing.
@unhammer: I wasn't seeing any difference in the thumbnail image (tests were passing). Could you unzip both `out.odt` and `expected.odt` to see what/why there's a difference on them?

**Comment by TinoDidriksen** [comment]
On a pristine and minimal Debian Sid build image, I get:
````
error [in.odt]:  missing 1 bytes in zipfile
  (attempting to process anyway)
error: invalid zip file with overlapped components (possible zip bomb)

zip error: Nothing to do! (try: zip -q -r - . -i .)
--- out.odt
+++ expected.odt
+          0 00000000 Configurations2/
+          0 00000000 Configurations2/accelerator/
+          0 00000000 Configurations2/floater/
+          0 00000000 Configurations2/images/
+          0 00000000 Configurations2/images/Bitmaps/
+          0 00000000 Configurations2/menubar/
+          0 00000000 Configurations2/popupmenu/
+          0 00000000 Configurations2/progressbar/
+          0 00000000 Configurations2/statusbar/
+          0 00000000 Configurations2/toolbar/
+          0 00000000 Configurations2/toolpanel/
+          0 00000000 META-INF/
+       1061 c5e513e1 META-INF/manifest.xml
+          0 00000000 Thumbnails/
+        553 c68d23ff Thumbnails/thumbnail.png
+       3845 92af4a5c content.xml
+        899 d268f7b4 manifest.rdf
+       1003 682c1f3f meta.xml
+         39 0c32c65e mimetype
+      11657 623dfef4 settings.xml
+      11576 ca8560e5 styles.xml
FAIL odt/run (exit status: 1)
````

**Comment by TinoDidriksen** [comment]
Hm, we haven't had binary files in the repo before, so https://github.com/apertium/apertium/blob/master/.gitattributes says everything is text - this is no longer true. @xavivars, you need to add `*.odt binary` to the end of `.gitattributes` and re-commit the binary ODT files if you still have your unchanged copies.

**Pull request merged**
