### PR TITLE
att_compiler: Support for weights to lttoolbox binary format.

### PR DESCRIPTION
**Pull request by techievena**
Make necessary modifications in apertium to be compatible
with the new lttoolbox.

Related to https://github.com/apertium/lttoolbox/issues/2

### CODE REVIEW

**Comment by Techievena** [comment]
getting these warnings from apertium-tagger.
Warning: There is not coarse tag for the fine tag 'estar<vblex><pri><p1><sg># de acuerdo con'
This is because of an incomplete tagset definition or a dictionary error
apertium-tagger is creating the difference in outputs.

**Comment by Techievena** [comment]
Hi Kevin
Opened an issue in the apertium core repository regarding this.
https://github.com/apertium/apertium/issues/17

**Comment by Techievena** [comment]
Sorry wrong thread



Regards,

Abinash Senapati
Pre-final Year Undergraduate,
Department of Electronics and Electrical Communication Engineering,
Indian Institute of Technology, Kharagpur-721302, India
*Website: *https://techievena.github.io

**Comment by Techievena** [comment]
@unhammer to confirm the changes I did in lttoolbox wasn't breaking anything, @ftyers asked me to do a corpus test. There were some errors in apertium and apertium-lex-tools repository, so I fixed them. Now nothing was breaking but the corpus test was showing some some difference in translation. So @TinoDidriksen and @ftyers asked me to go through each of the pipeline and find out at which point in the pipeline the difference begins.

So after checking, I found out that apertium-tagger was responsible for creating these difference. So these are the warnings generated by the debug option in apertium-tagger.

**Comment by unhammer** [comment]
So the changes to transfer_data.cc are necessary because of API changes in lttoolbox?

**Comment by Techievena** [comment]
@unhammer 
> There were some errors in apertium and apertium-lex-tools repository, so I fixed them.

The changes to transfer_data.cc prevent the apertium build from failing, but the problem with warning in apertium-tagger still retains. By debugging I found out that, they are generated in file_morpho_stream.cc when it uses the objects of the classes defined in match_state.cc and match_exe.cc. So perhaps the PR in lttoolbox need some more modifications first.

**Pull request merged**
